module.exports = [
  {
    username: "alexpap",
    firstName: "Alex",
    lastName: "Pap",
    email: "alexpap@gmail.com",
    role: "admin",
    password: "pass1",
  },
  {
    username: "jimgal",
    firstName: "Dimitris",
    lastName: "Galanis",
    email: "jimgal@gmail.com",
    role: "admin",
    password: "pass2",
  },
  {
    username: "triant",
    firstName: "Triantafillos",
    lastName: "Iliadis",
    email: "triant@gmail.com",
    role: "admin",
    password: "pass3",
  },
  {
    username: "user1",
    firstName: "user1FN",
    lastName: "user1LN",
    email: "user1@gmail.com",
    role: "user",
    password: "pass1",
  },
  {
    username: "user2",
    firstName: "user2FN",
    lastName: "user2LN",
    email: "user2@gmail.com",
    role: "user",
    password: "pass2",
  },
  {
    username: "user3",
    firstName: "user3FN",
    lastName: "user3LN",
    email: "user3@gmail.com",
    role: "user",
    password: "pass3",
  },
];
